
gripper_dynamixel_action_node:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baudrate: 57600
    dxl_id: 1

    addr_operating_mode: 11
    addr_torque_enable: 64
    addr_goal_current: 102
    addr_goal_position: 116
    addr_present_current: 126
    addr_present_position: 132

    operating_mode_current: 0
    operating_mode_position: 3
    operating_mode_current_based_position: 5

    position_is_radians: true
    ticks_per_rev: 4096
    gear_ratio: 1.0
    direction: 1
    zero_offset_ticks: 0

    open_position: 0.0
    close_position: 1.0

    goal_tolerance_ticks: 20
    motion_timeout_sec: 3.0
    poll_rate_hz: 30.0

    use_torque_mode: false
    default_torque: 0.0
    close_default: true
